version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.32.1-focal
    
jobs:
  sanity:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm install -D @playwright/test
          npx playwright test
          npm run allure:generate
workflows:
  my-custom-workflow:
    jobs:
      - sanity
